import * as fs from 'fs';

function run() {
  const assigneesData = JSON.parse(fs.readFileSync('recovered_ticket_assignees_dry_run.json', 'utf8'));

  const totalRecords = assigneesData.length;
  
  const uniqueTickets = new Set(assigneesData.map((a: any) => a.ticketId));
  const ticketsWithAssignees = uniqueTickets.size;

  const uniqueUsers = new Set(assigneesData.map((a: any) => a.assignedToId));
  const uniqueUsersAssigned = uniqueUsers.size;

  const sample = assigneesData.slice(0, 20);

  const report = `
# Assignee Recovery Audit

## Discrepancy Investigation
The discrepancy occurred because \`audit_relations.ts\` read the original \`recovered_tickets_dry_run.json\` file generated by the *first* script, which did not include assignee or department mappings. The extended script correctly recovered the 94 assignees, but they were stored in \`recovered_ticket_assignees_dry_run.json\`.

## Recovery Metrics
- **Actual TicketAssignee records ready for insert:** ${totalRecords}
- **Number of tickets with assignees:** ${ticketsWithAssignees}
- **Number of unique users assigned:** ${uniqueUsersAssigned}

## Sample Recovered Mappings (Top 20)
\`\`\`json
${JSON.stringify(sample, null, 2)}
\`\`\`
`;

  fs.writeFileSync('ASSIGNEE_RECOVERY_AUDIT.md', report.trim() + '\\n');
  console.log('Generated ASSIGNEE_RECOVERY_AUDIT.md');
}

run();
