"use client";

// Sales CRM — Report export/share output
// Ported from intern source (src/lib/report-output.ts). PDF export is
// fully functional (pure string/Blob generation, zero dependencies).
// Excel export is disabled: the intern source did `await import("xlsx")`
// inside downloadReportExport only when format === "excel" — but xlsx was
// removed pending an import/export package decision (see Step 1 security
// cleanup) and this step's instructions explicitly say not to add it back.
// The excel branch now throws a clear, catchable error instead of
// attempting the import, so the UI can surface a real message rather than
// a generic failure (see ExportModal.tsx / page.tsx's catch handling).

export type ReportExportFormat = "excel" | "pdf";

export interface ReportExportAction {
  format: ReportExportFormat;
  fileName: string;
}

export interface ReportShareAction {
  targetType: "Individual" | "Team" | "Group";
  targetName: string;
}

export interface ReportArtifactSection {
  title: string;
  rows: Record<string, unknown>[];
}

export interface ReportArtifact {
  title: string;
  subtitle?: string;
  generatedBy?: string;
  generatedAt?: string;
  context?: Record<string, unknown>;
  summary?: Record<string, unknown>;
  filters?: Record<string, unknown>;
  sort?: Record<string, unknown>;
  sections?: ReportArtifactSection[];
}

function sanitizeFileName(value: string) {
  return (value || "Sales_CRM_Report")
    .replace(/[^a-zA-Z0-9._-]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 80) || "Sales_CRM_Report";
}

function valueToCell(value: unknown): string | number | boolean {
  if (value === null || value === undefined) return "";
  if (typeof value === "number" || typeof value === "boolean") return value;
  if (typeof value === "string") return value;
  return JSON.stringify(value);
}

function normalizeRows(rows: Record<string, unknown>[]) {
  return rows.map((row) => (
    Object.fromEntries(Object.entries(row).map(([key, value]) => [key, valueToCell(value)]))
  ));
}

function toKeyValueRows(data: Record<string, unknown> | undefined) {
  return Object.entries(data || {}).map(([key, value]) => ({
    Field: key,
    Value: valueToCell(value),
  }));
}

function downloadBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapLine(value: string, maxLength = 92) {
  const words = value.split(/\s+/);
  const lines: string[] = [];
  let current = "";

  words.forEach((word) => {
    const next = current ? `${current} ${word}` : word;
    if (next.length > maxLength) {
      if (current) lines.push(current);
      current = word;
    } else {
      current = next;
    }
  });

  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

function buildPdf(lines: string[]) {
  const contentLines = [
    "BT",
    "/F1 12 Tf",
    "48 790 Td",
    ...lines.flatMap((line, index) => {
      const wrapped = wrapLine(line);
      return wrapped.map((wrappedLine, wrappedIndex) => {
        const leading = index === 0 && wrappedIndex === 0 ? "" : "0 -16 Td ";
        return `${leading}(${escapePdfText(wrappedLine)}) Tj`;
      });
    }),
    "ET",
  ];
  const stream = contentLines.join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];

  let output = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(output.length);
    output += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = output.length;
  output += `xref\n0 ${objects.length + 1}\n`;
  output += "0000000000 65535 f \n";
  offsets.slice(1).forEach((offset) => {
    output += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  output += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return output;
}

function buildPdfLines(artifact: ReportArtifact) {
  const generatedAt = artifact.generatedAt || new Date().toISOString();
  const lines = [
    artifact.title,
    artifact.subtitle || "Sales CRM report export",
    `Generated at: ${generatedAt}`,
    artifact.generatedBy ? `Generated by: ${artifact.generatedBy}` : "",
    "",
    "Summary",
    ...toKeyValueRows(artifact.summary).map((row) => `${row.Field}: ${row.Value}`),
    "",
    "Context",
    ...toKeyValueRows(artifact.context).map((row) => `${row.Field}: ${row.Value}`),
    "",
    "Filters",
    ...toKeyValueRows(artifact.filters).map((row) => `${row.Field}: ${row.Value}`),
    "",
    "Sort",
    ...toKeyValueRows(artifact.sort).map((row) => `${row.Field}: ${row.Value}`),
  ].filter(Boolean);

  (artifact.sections || []).forEach((section) => {
    lines.push("", section.title);
    normalizeRows(section.rows).slice(0, 12).forEach((row) => {
      lines.push(Object.entries(row).map(([key, value]) => `${key}: ${value}`).join(" | "));
    });
  });

  return lines.slice(0, 48);
}

export async function downloadReportExport(action: ReportExportAction, artifact: ReportArtifact) {
  const baseName = sanitizeFileName(action.fileName || artifact.title);

  if (action.format === "excel") {
    throw new Error("Excel export is disabled until the import/export package is approved. Use PDF export instead.");
  }

  const fileName = `${baseName}.pdf`;
  downloadBlob(new Blob([buildPdf(buildPdfLines(artifact))], { type: "application/pdf" }), fileName);
  return fileName;
}

export async function createSharePackage(action: ReportShareAction, artifact: ReportArtifact) {
  const generatedAt = new Date().toISOString();
  const token = `salescrm-share-${sanitizeFileName(artifact.title).toLowerCase()}-${Date.now()}`;
  const payload = {
    token,
    targetType: action.targetType,
    targetName: action.targetName,
    generatedAt,
    artifact: {
      ...artifact,
      generatedAt: artifact.generatedAt || generatedAt,
    },
  };
  const fileName = `${sanitizeFileName(artifact.title)}_share_package.json`;

  downloadBlob(
    new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }),
    fileName,
  );

  let copied = false;
  if (navigator.clipboard?.writeText) {
    try {
      await navigator.clipboard.writeText(`${token}\n${JSON.stringify(payload, null, 2)}`);
      copied = true;
    } catch {
      copied = false;
    }
  }

  return { fileName, token, copied };
}
