import * as ExcelJS from 'exceljs';
import {
  monthTotals,
  type MonthTotals,
  type PayrollSummaryRow,
  type RegisterRow,
} from './payroll-aggregation';

/**
 * The monthly attendance workbook Finance receives.
 *
 * XLSX rather than PDF: this is a working file somebody sorts, filters and
 * reconciles against payroll, not a document to read once. exceljs is already a
 * dependency, so nothing new is installed. A human-readable PDF register is a
 * separate decision and would need a new library.
 *
 * Minutes are written as NUMBERS, not as "9h 00m". Finance needs to add them
 * up, and a formatted string in a spreadsheet is a value nobody can sum. The
 * hours column beside it is a formula-free convenience, computed here so the
 * two can never disagree.
 *
 * Unresolved days are carried on the summary AND called out on a cover sheet.
 * A month with unreviewed exceptions is not a finished payroll input, and
 * burying that in column P would make it easy to miss.
 */

const HEADER_FILL: ExcelJS.Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFF1F5F9' },
};

function header(sheet: ExcelJS.Worksheet, columns: Array<{ header: string; key: string; width: number }>) {
  sheet.columns = columns;
  const row = sheet.getRow(1);
  row.font = { bold: true };
  row.fill = HEADER_FILL;
  row.alignment = { vertical: 'middle' };
  sheet.views = [{ state: 'frozen', ySplit: 1 }];
}

const hours = (minutes: number | null) =>
  minutes === null ? null : Math.round((minutes / 60) * 100) / 100;

export interface WorkbookInput {
  /** yyyy-MM */
  month: string;
  companyLabel: string;
  summaries: PayrollSummaryRow[];
  register: RegisterRow[];
  generatedAt: Date;
  generatedBy: string;
  /** Null until HR finalises. An unfinalised report says so on its face. */
  finalizedAt: Date | null;
  finalizedBy: string | null;
}

export function buildPayrollWorkbook(input: WorkbookInput): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Apex OS Attendance';
  wb.created = input.generatedAt;

  const totals = monthTotals(input.summaries, []);
  addCoverSheet(wb, input, totals);
  addSummarySheet(wb, input);
  addRegisterSheet(wb, input);

  return wb;
}

/**
 * Says what this file is and whether it can be trusted as final.
 *
 * A spreadsheet that arrives by email outlives the conversation that produced
 * it. Six months on, somebody has to be able to tell from the file alone
 * whether HR had finished reviewing the month.
 */
function addCoverSheet(wb: ExcelJS.Workbook, input: WorkbookInput, totals: MonthTotals) {
  const sheet = wb.addWorksheet('Report');
  sheet.columns = [
    { header: '', key: 'label', width: 32 },
    { header: '', key: 'value', width: 48 },
  ];

  const rows: Array<[string, string]> = [
    ['Report', 'Monthly Attendance — payroll input'],
    ['Company', input.companyLabel],
    ['Month', input.month],
    ['Employees', String(totals.employees)],
    ['Generated at', input.generatedAt.toISOString()],
    ['Generated by', input.generatedBy],
    [
      'Status',
      input.finalizedAt
        ? `FINALIZED by ${input.finalizedBy ?? 'HR'} at ${input.finalizedAt.toISOString()}`
        : 'DRAFT — not finalized by HR',
    ],
    ['Unresolved days', String(totals.unresolvedDays)],
    ['Employees with unresolved days', String(totals.employeesWithUnresolved)],
    ['Manual recovery days', String(totals.manualRecoveryDays)],
  ];

  for (const [label, value] of rows) {
    const row = sheet.addRow({ label, value });
    row.getCell('label').font = { bold: true };
  }

  sheet.addRow([]);
  const note = sheet.addRow({
    label: 'Note',
    value:
      'Attendance facts only. No salary or deduction is calculated here — ' +
      'payroll rules are applied by Finance.',
  });
  note.getCell('value').alignment = { wrapText: true };

  if (totals.employeesWithUnresolved > 0) {
    const warn = sheet.addRow({
      label: 'Attention',
      value:
        `${totals.employeesWithUnresolved} employee(s) have days that were never resolved. ` +
        'Those rows are not a settled attendance result.',
    });
    warn.getCell('value').font = { color: { argb: 'FFB45309' }, bold: true };
    warn.getCell('value').alignment = { wrapText: true };
  }
}

function addSummarySheet(wb: ExcelJS.Workbook, input: WorkbookInput) {
  const sheet = wb.addWorksheet('Payroll Summary');
  header(sheet, [
    { header: 'Employee ID', key: 'employeeId', width: 14 },
    { header: 'Employee Name', key: 'name', width: 26 },
    { header: 'Department', key: 'department', width: 20 },
    { header: 'Working Days', key: 'workingDays', width: 13 },
    { header: 'Present', key: 'present', width: 10 },
    { header: 'Absent', key: 'absent', width: 10 },
    { header: 'Casual Leave', key: 'casualLeave', width: 13 },
    { header: 'Emergency Leave', key: 'emergencyLeave', width: 16 },
    { header: 'Comp Off', key: 'compOff', width: 10 },
    { header: 'Half Days', key: 'halfDays', width: 11 },
    { header: 'Holidays', key: 'holidays', width: 10 },
    { header: 'Weekly Offs', key: 'weeklyOffs', width: 12 },
    { header: 'Late Days', key: 'lateDays', width: 11 },
    { header: 'Needs Review', key: 'needsReview', width: 13 },
    { header: 'Manual Recovery', key: 'manualRecoveryDays', width: 16 },
    { header: 'Regularized', key: 'regularizedDays', width: 12 },
    { header: 'Unresolved', key: 'unresolvedDays', width: 12 },
  ]);

  for (const s of input.summaries) {
    const row = sheet.addRow(s);
    // An unresolved row is marked in the file itself, so it survives being
    // sorted, filtered or pasted into another sheet.
    if (s.unresolvedDays > 0) {
      row.getCell('unresolvedDays').font = { bold: true, color: { argb: 'FFB45309' } };
    }
  }
  sheet.autoFilter = { from: 'A1', to: { row: 1, column: 17 } };
}

function addRegisterSheet(wb: ExcelJS.Workbook, input: WorkbookInput) {
  const sheet = wb.addWorksheet('Daily Register');
  header(sheet, [
    { header: 'Employee ID', key: 'employeeId', width: 14 },
    { header: 'Employee', key: 'name', width: 24 },
    { header: 'Date', key: 'date', width: 12 },
    { header: 'Day', key: 'day', width: 11 },
    { header: 'Classification', key: 'classification', width: 16 },
    { header: 'Status', key: 'status', width: 15 },
    { header: 'Punch In', key: 'punchIn', width: 20 },
    { header: 'In Source', key: 'punchInSource', width: 11 },
    { header: 'Punch Out', key: 'punchOut', width: 20 },
    { header: 'Out Source', key: 'punchOutSource', width: 11 },
    { header: 'Presence (min)', key: 'presenceMinutes', width: 14 },
    { header: 'Presence (h)', key: 'presenceHours', width: 13 },
    { header: 'Required (min)', key: 'requiredMinutes', width: 14 },
    { header: 'Worked (min)', key: 'workedMinutes', width: 13 },
    { header: 'Workday Span (min)', key: 'workdaySpanMinutes', width: 18 },
    { header: 'Break (min)', key: 'breakMinutes', width: 12 },
    { header: 'Leave', key: 'leaveType', width: 14 },
    { header: 'Manual', key: 'manualEntry', width: 9 },
    { header: 'Regularized', key: 'regularized', width: 12 },
    { header: 'Needs Review', key: 'needsReview', width: 13 },
    { header: 'Remarks', key: 'remarks', width: 40 },
  ]);

  for (const r of input.register) {
    sheet.addRow({
      ...r,
      // Numbers, so Finance can sum them. Presence stays null rather than
      // becoming 0 when it could not be measured -- zero is a measurement.
      presenceHours: hours(r.presenceMinutes),
      manualEntry: r.manualEntry ? 'Yes' : '',
      regularized: r.regularized ? 'Yes' : '',
      needsReview: r.needsReview ? 'Yes' : '',
    });
  }
  sheet.autoFilter = { from: 'A1', to: { row: 1, column: 21 } };
}

export async function workbookToBuffer(wb: ExcelJS.Workbook): Promise<Buffer> {
  return Buffer.from(await wb.xlsx.writeBuffer());
}

/** Stable, sortable, and says what it is without being opened. */
export function workbookFilename(month: string, finalized: boolean): string {
  return `apex-os-attendance-${month}${finalized ? '' : '-DRAFT'}.xlsx`;
}
