-- Remove AttendanceMonthClose.reportSha256.
--
-- THE MONTH-CLOSE FINGERPRINT IS GONE, BY PRODUCT DECISION.
--
-- The column held a SHA-256 of the finalized attendance data, compared at send
-- time to refuse a report that no longer matched what HR approved. The owner
-- asked for that cryptographic finalization guard to be removed and NOT
-- replaced with another hash, so finalization is now plain business state:
-- FINALIZED / SENT, with who and when.
--
-- Nothing reads or writes this column after the commit that adds this
-- migration, so applying it in either order is safe.
--
-- WHAT WAS GIVEN UP, RECORDED HERE because a migration outlives a pull request:
-- a correction committed after finalization and before sending is no longer
-- detected. The month advisory lock narrows that window to the send itself
-- rather than closing it. The send idempotency key, which used to be built from
-- this digest, is now built from monthCloseId + finalizedAt -- stable across a
-- retry, different after a re-finalization, which were the only two properties
-- the digest supplied to it.
--
-- Apply on staging and confirm `prisma migrate status` is clean before
-- production. NOT applied to production by this change.

ALTER TABLE "attendance_month_closes" DROP COLUMN "reportSha256";
